import {
    BADGE_GREEN,
    BADGE_BLUE,
    BADGE_ORANGE,
    BADGE_RED,
} from '../components/common/Badge';

const mockData = [
    {
        id: 1,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 2,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 3,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 4,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 5,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 6,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 7,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 8,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 9,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 10,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 11,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 12,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 13,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 14,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 15,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 16,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 17,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 18,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 19,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 20,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 21,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 22,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 23,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 24,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 25,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 26,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 27,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 28,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 29,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 30,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 31,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 32,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 33,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 34,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 35,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 36,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 37,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 38,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 39,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 40,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 41,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 42,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 43,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 44,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 45,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 46,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 47,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 48,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 49,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 50,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 51,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 52,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 53,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 54,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 55,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 56,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 57,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 58,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 59,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 60,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 61,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 62,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 63,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 64,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 65,
        asciiFace: '(づ｡◕‿‿◕｡)づ',
        title: 'Daily News',
        description:
            'Improve your communication skills and have better conversations.',
        badgeColor: BADGE_GREEN,
        badgeIcon: '$',
        pillContent: '5 Days ago',
        badgeContent: '300.00',
    },
    {
        id: 66,
        asciiFace: " ̿ ̿'̿'̵͇̿̿з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿",
        title: 'Conversation',
        description:
            'Our most popular material. New lessons added every day based on current events.',
        badgeColor: BADGE_BLUE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '500.00',
    },
    {
        id: 67,
        asciiFace: '̿̿̿（╯°□°）╯︵( .o.)',
        title: 'Describing Pictures',
        description:
            'Increase your vocabulary and speaking skills by describing pictures.',
        badgeColor: BADGE_ORANGE,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
    {
        id: 68,
        asciiFace: '(▀̿Ĺ̯▀̿ ̿)',
        title: 'Health & Lifestyle',
        description:
            'Learn health-related vocabulary and expressions health-related issues',
        badgeColor: BADGE_RED,
        badgeIcon: '$',
        pillContent: '3 Days ago',
        badgeContent: '400.00',
    },
];

export default mockData;
